### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by smebberson** [webplates/docker-readthedocs#4]
Exactly how can I use this?

I'm looking for a Docker image that will build my readthedocs folder, so I can test everything looks good before pushing to Git and having the readthedocs build process build publicly.

I ran `docker run --rm --interactive --tty --volume /path-to-docs/docs:/doc webplates/readthedocs` and then `make html` inside the container but received errors:

```
make: *** No rule to make target 'html'.  Stop.
```

I know I'm doing something stupid. My `/path-to-docs/docs` folder contains only `.rst` files. Any information you could provide would be awesome.

**Comment by sagikazarmark** [comment]
By default the Read the docs sphinx setup comes with a Makefile, like [this](https://github.com/php-http/documentation/blob/master/Makefile) one.

Do you have anything like that?

Anyway, the sphinx executable is available within the container so you should be able to run the same commands that you are used to.

Hope this helps.

**Comment by sagikazarmark** [comment]
Oh, one more thing that could cause the issue if you HAVE a Makefile in your directory has just been fix: #3

**Comment by smebberson** [comment]
@sagikazarmark, thanks for your help. That worked a treat :)
